DROP TABLE IF EXISTS WINE;
--SPLIT
CREATE TABLE IF NOT EXISTS WINE (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE,
    year INTEGER,
    variety TEXT,
    rating NUMERIC,
    price NUMERIC,
    colour TEXT,
    vineyard TEXT FOREIGN KEY REFERENCES VINEYARD
);
--SPLIT
DROP TABLE IF EXISTS REGION;
--SPLIT
CREATE TABLE IF NOT EXISTS REGION (
    name TEXT PRIMARY KEY
);
--SPLIT
DROP TABLE IF EXISTS VINEYARD;
--SPLIT
CREATE TABLE IF NOT EXISTS VINEYARD (
    name TEXT PRIMARY KEY,
    region TEXT FOREIGN KEY REFERENCES REGION,
    latitude NUMERIC,
    longitude NUMERIC
);
--SPLIT
DROP TABLE IF EXISTS USER;
--SPLIT
CREATE TABLE IF NOT EXISTS USER (
    id INTEGER PRIMARY KEY,
    username TEXT UNIQUE,
    password TEXT,
    role TEXT
);
--SPLIT
DROP TABLE IF EXISTS DRINKS;
--SPLIT
CREATE TABLE IF NOT EXISTS DRINKS (
    wine TEXT FOREIGN KEY REFERENCES WINE,
    user TEXT FOREIGN KEY REFERENCES USER,
    favorite BOOLEAN,
    notes TEXT,
    rating INTEGER,
    PRIMARY KEY (wine, user)
)
